CREATE TABLE Users
(
	UserID INT PRIMARY KEY IDENTITY,
	LibraryID INT FOREIGN KEY REFERENCES Library(LibraryID),
	Address VARCHAR(255),
	Username VARCHAR(255)
)

CREATE TABLE Library
(
	LibraryID INT PRIMARY KEY IDENTITY,
	CollectionID INT FOREIGN KEY REFERENCES Collection(CollectionID)
)

CREATE TABLE Collection
(
	CollectionID INT PRIMARY KEY IDENTITY,
	GameID INT FOREIGN KEY REFERENCES Game(GameID),
	GameTimeID INT FOREIGN KEY REFERENCES GameTime(GameTimeID),
	PurchaseID INT FOREIGN KEY REFERENCES Purchase(PurchaseID)
)

CREATE TABLE GameTime
(
	GameTimeID INT PRIMARY KEY IDENTITY,
	HoursPlayed DEC,
	LastTimePlayed DATE,
	FirstTimePlayed DATE
)

CREATE TABLE Game
(
	GameID INT PRIMARY KEY IDENTITY,
	Title VARCHAR(255),
	MemorySizeKb INT,
	Description VARCHAR(255),
	GenreID INT FOREIGN KEY REFERENCES Genre(GenreID)

)

CREATE TABLE Genre
(
	GenreID INT PRIMARY KEY IDENTITY,
	Genre VARCHAR(255)
)

CREATE TABLE Purchase
(
	PurchaseID INT PRIMARY KEY IDENTITY,
	GameID INT FOREIGN KEY REFERENCES Game(GameID),
	InitialPrice MONEY,
	Transactions MONEY
)